# Generated by Django 3.1.6 on 2021-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='tuition',
            field=models.IntegerField(default=0),
        ),
    ]
